env: "development"

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}
  max_attempts: ${DB_RETRIES}
  ssl: disable

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: 0
  retries: ${REDIS_RETRIES}

grpc:
  host: localhost
  port: "44044"
  timeout: 10s

mail:
  host: ${EMAIL_SERVER_HOST}
  port: ${EMAIL_SERVER_PORT}
  user: ${EMAIL_SERVER_USER}
  password: ${EMAIL_SERVER_PASSWORD}
  from: ${EMAIL_FROM}
  ssl: true



