env: "development"

database:
  host: localhost
  port: "7111"
  user: "postgres"
  password: "postgres"
  dbname: "fitnow"
  max_attempts: 5
  ssl: disable

redis:
  host: localhost
  port: "6379"
  password: ""
  db: 0
  retries: 5

grpc:
  host: localhost
  port: "44044"
  timeout: 10s

mail:
  host: ${EMAIL_SERVER_HOST}
  port: ${EMAIL_SERVER_PORT}
  user: ${EMAIL_SERVER_USER}
  password: ${EMAIL_SERVER_PASSWORD}
  from: ${EMAIL_FROM}
  ssl: true



